### PR TITLE
ADR for renaming the project

### LINKED ISSUE #26: Rename the project
Unfortunately, someone has beaten us to the [`ashlar` package name on PyPi](https://pypi.org/project/ashlar/). If distributing through PyPi is important to us, we should consider renaming the project.

### PR DESCRIPTION
**Pull request by jeancochrane**
# Overview

This PR introduces an ADR for renaming the Ashlar project.

## Notes

- Best viewed [on GitHub](https://github.com/azavea/ashlar-2018-fellowship/blob/c1305f5ef4b48a887b50a9020e3875d0e74f2d9c/docs/rename-package.md).

- Choosing names is very hard and I don't expect this decision to be unilateral. Instead, I consider this ADR the start of a conversation around choosing a new name.

Closes #26.

### CODE REVIEW

**Review by flibbertigibbet — APPROVED** [review]
Looks good!

**Review by ddohler — APPROVED** [review]
Agreed, I also like `grout`!

**Comment by kshepard** [comment]
I'm loving `grout`.

**Comment by jeancochrane** [comment]
Awesome, thanks for your comments all! Pulling this in now.

**Pull request merged**
