### PR TITLE
Demo app framework ADR

### PR DESCRIPTION
**Pull request by jeancochrane**
# Overview

This PR includes a draft ADR for choosing the frontend framework that I'll use to build the Ashlar demo app.

## Notes

- Best viewed [on GitHub](https://github.com/azavea/ashlar-2018-fellowship/blob/86cd5cbb25789a12895ab541c0881916ff106e70/docs/demo-framework.md).

- I've never written an ADR before, so I apologize in advance for any misunderstandings! I'm considering this a "draft" that I'd like comments on, as opposed to a formal "decision" -- I couldn't tell if that was a standard approach to an ADR or not, but it seems reasonable to me to consider this undecided until the PR is approved.

- I had a hard time choosing between Angular and Vue, and went back and forth on the decision a few times. I'd appreciate your insight into the relative costs/benefits, in case the are any factors that I'm neglecting to consider properly.

Closes https://github.com/azavea/ashlar-2018-fellowship/issues/24.

### CODE REVIEW

**Review by ddohler — COMMENTED** [review]
This is a great ADR! I find that the best ADRs mimic the flow and content of an in-person technical discussion between two or more developers, and allow a developer to get up to speed quickly on the technical issues at hand. This does exactly that. I found it easy to read and clear about the trade-offs involved in each potential choice.

In other words, I don't really have any comments about your use of the ADR format; I thought it was spot-on. One additional thing I think would be useful for you to consider for React and Vue, is the addition of Redux / Vuex to the project.

As far as your conclusions, I think Vue is a solid, defensible choice; we're writing Cartwheel (non-public repo) in Vue and I've found it to be pretty familiar coming from AngularJS, but generally simpler and easier to use, so I'm hopeful that we'll be able to offer you useful feedback.

**Review by flibbertigibbet — APPROVED** [review]
Great overview!

**Comment by jeancochrane** [comment]
Thanks for taking a look guys! Looking forward to getting started.

To your comment @ddohler: I assumed that React/Vue implementations would use Flux-like state management patters (Redux,Vuex), and probably also a corresponding routing library at the very least. I felt like the benefits/drawbacks of this were encapsulated in the broader discussion about React/Vue being relatively small core libraries with larger ecosystems of plugins and helper libraries, so I didn't spend much extra time on it. Do you think it's worth adding short comparisons of state management offerings in each of the libraries, too? If you think that's important context I can go ahead and spend some time on it today.

**Comment by ddohler** [comment]
Gotcha -- I don't think it's necessary to compare state management in each library. My point was more that if you think you would be likely to adopt one of those libraries, it might make sense to evaluate the whole package of "React + Redux" or "Vue + Vuex" as if it were a monolithic framework. That way it would become a bit more comparable to something like Angular or Ember because you're including all the main libraries that you would expect to use to get up to the full functionality that those frameworks have, even if you're pulling it together from multiple places.

That's not to say that I think you should try to evaluate every single library that you could or might use upfront; that would be pretty unwieldy (not to mention really hard to predict accurately). But I wanted to flag Redux and Vuex because of their popularity and because they affect the overall app structure; writing a "React + Redux" app is (or can be) quite a bit different from writing a plain React app.

Sorry that my initial suggestion was a bit obtuse; I should have fleshed out what I meant more. Hope this makes better sense!

**Comment by jeancochrane** [comment]
That makes a lot of sense @ddohler! Thanks for clearing up your point, it's well-taken. I'll make some edits to reflect that the proper comparison is with React + Redux and Vue + Vuex. Would you like to review again when that's done, or are you comfortable with me pulling it in?

**Review by ddohler — APPROVED** [review]
As long as you don't think the Vuex / Redux stuff will change your choice of framework, I'm fine with merging this in once you've made the changes to add those technologies. Thanks for putting this together -- great job!

**Pull request merged**
